# Generated by Django 4.0 on 2022-01-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EightMESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=1000, null=True)),
                ('Value', models.CharField(blank=True, max_length=1000, null=True)),
                ('Pattern', models.CharField(blank=True, max_length=1000, null=True)),
                ('RefDes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': '8MESP32',
            },
        ),
        migrations.CreateModel(
            name='FourMESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=1000, null=True)),
                ('Value', models.CharField(blank=True, max_length=1000, null=True)),
                ('Pattern', models.CharField(blank=True, max_length=1000, null=True)),
                ('RefDes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': '4MESP32',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, max_length=210, null=True)),
                ('client_name', models.CharField(blank=True, max_length=210, null=True)),
                ('sub_total', models.CharField(blank=True, max_length=210, null=True)),
                ('discount', models.CharField(blank=True, max_length=210, null=True)),
                ('final_price', models.CharField(blank=True, max_length=210, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('timestamp', models.CharField(blank=True, max_length=210, null=True)),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, max_length=210, null=True)),
                ('model_name', models.CharField(blank=True, max_length=210, null=True)),
                ('quantity', models.CharField(blank=True, max_length=210, null=True)),
                ('unit_price', models.CharField(blank=True, max_length=210, null=True)),
                ('price', models.CharField(blank=True, max_length=210, null=True)),
                ('lead_id', models.CharField(blank=True, max_length=210, null=True)),
                ('client_name', models.CharField(blank=True, max_length=210, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('timestamp', models.CharField(blank=True, max_length=210, null=True)),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
        migrations.CreateModel(
            name='SixMESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=1000, null=True)),
                ('Value', models.CharField(blank=True, max_length=1000, null=True)),
                ('Pattern', models.CharField(blank=True, max_length=1000, null=True)),
                ('RefDes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': '6mesp32',
            },
        ),
        migrations.CreateModel(
            name='TwoMESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=1000, null=True)),
                ('Value', models.CharField(blank=True, max_length=1000, null=True)),
                ('Pattern', models.CharField(blank=True, max_length=1000, null=True)),
                ('RefDes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': '2mesp32',
            },
        ),
    ]
