# Generated by Django 4.0 on 2022-01-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invantory', '0002_bomstatusmanager_orderdetails_bom_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='device_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
