# Generated by Django 4.0 on 2022-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='user_otp',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
