# Generated by Django 4.0 on 2022-01-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_loginmodel_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=120, null=True)),
                ('dept_id', models.CharField(blank=True, max_length=120, null=True)),
                ('lead_id', models.CharField(blank=True, max_length=120, null=True)),
                ('process_id', models.CharField(blank=True, max_length=120, null=True)),
                ('process_name', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'internal_process',
            },
        ),
    ]
