# Generated by Django 4.0 on 2022-01-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_internalprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(blank=True, max_length=120, null=True)),
                ('process_name', models.CharField(blank=True, max_length=120, null=True)),
                ('dept_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'process_description',
            },
        ),
    ]
