# Generated by Django 4.0 on 2022-01-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionExternalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, max_length=210, null=True)),
                ('device_id', models.CharField(blank=True, max_length=210, null=True)),
                ('is_soldring', models.CharField(blank=True, max_length=210, null=True)),
                ('is_visual_inspection', models.CharField(blank=True, max_length=210, null=True)),
                ('is_programing', models.CharField(blank=True, max_length=210, null=True)),
                ('is_testing', models.CharField(blank=True, max_length=210, null=True)),
                ('is_f_testing', models.CharField(blank=True, max_length=210, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=210, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_external_process',
            },
        ),
    ]
