# Generated by Django 4.0 on 2022-01-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=210, null=True)),
                ('model_name', models.CharField(blank=True, max_length=210, null=True)),
                ('pcb_type', models.CharField(blank=True, max_length=210, null=True)),
                ('device_id', models.CharField(blank=True, max_length=210, null=True)),
                ('f_testing_time', models.CharField(blank=True, max_length=210, null=True)),
                ('f_testing_by', models.CharField(blank=True, max_length=210, null=True)),
                ('user_auth_token', models.CharField(blank=True, max_length=210, null=True)),
                ('f_testing_status', models.CharField(blank=True, max_length=210, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=210, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_final_testing',
            },
        ),
        migrations.CreateModel(
            name='Programing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=210, null=True)),
                ('model_name', models.CharField(blank=True, max_length=210, null=True)),
                ('pcb_type', models.CharField(blank=True, max_length=210, null=True)),
                ('device_id', models.CharField(blank=True, max_length=210, null=True)),
                ('programing_time', models.CharField(blank=True, max_length=210, null=True)),
                ('programing_by', models.CharField(blank=True, max_length=210, null=True)),
                ('user_auth_token', models.CharField(blank=True, max_length=210, null=True)),
                ('programing_status', models.CharField(blank=True, max_length=210, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=210, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_programing',
            },
        ),
        migrations.CreateModel(
            name='Soldering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=210, null=True)),
                ('model_name', models.CharField(blank=True, max_length=210, null=True)),
                ('pcb_type', models.CharField(blank=True, max_length=210, null=True)),
                ('device_id', models.CharField(blank=True, max_length=210, null=True)),
                ('soldering_time', models.CharField(blank=True, max_length=210, null=True)),
                ('soldering_by', models.CharField(blank=True, max_length=210, null=True)),
                ('user_auth_token', models.CharField(blank=True, max_length=210, null=True)),
                ('soldering_status', models.CharField(blank=True, max_length=210, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=210, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_soldering',
            },
        ),
        migrations.CreateModel(
            name='Tetsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=210, null=True)),
                ('model_name', models.CharField(blank=True, max_length=210, null=True)),
                ('pcb_type', models.CharField(blank=True, max_length=210, null=True)),
                ('device_id', models.CharField(blank=True, max_length=210, null=True)),
                ('testing_time', models.CharField(blank=True, max_length=210, null=True)),
                ('testing_by', models.CharField(blank=True, max_length=210, null=True)),
                ('user_auth_token', models.CharField(blank=True, max_length=210, null=True)),
                ('testing_status', models.CharField(blank=True, max_length=210, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=210, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_testing',
            },
        ),
        migrations.CreateModel(
            name='VisualInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=210, null=True)),
                ('model_name', models.CharField(blank=True, max_length=210, null=True)),
                ('pcb_type', models.CharField(blank=True, max_length=210, null=True)),
                ('device_id', models.CharField(blank=True, max_length=210, null=True)),
                ('inspection_time', models.CharField(blank=True, max_length=210, null=True)),
                ('inspection_by', models.CharField(blank=True, max_length=210, null=True)),
                ('user_auth_token', models.CharField(blank=True, max_length=210, null=True)),
                ('inspection_status', models.CharField(blank=True, max_length=210, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=210, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_visual_inspection',
            },
        ),
    ]
