# Generated by Django 4.0 on 2022-01-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0002_finaltesting_programing_soldering_tetsing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionexternalprocess',
            name='bom_verification',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
    ]
