# Generated by Django 4.0 on 2022-01-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0003_productionexternalprocess_bom_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionexternalprocess',
            name='model',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='productionexternalprocess',
            name='model_name',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
    ]
