# Generated by Django 4.0 on 2022-01-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0004_productionexternalprocess_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, max_length=260, null=True)),
                ('emp_id', models.CharField(blank=True, max_length=260, null=True)),
                ('emailId', models.CharField(blank=True, max_length=260, null=True)),
                ('emp_contact', models.CharField(blank=True, max_length=260, null=True)),
                ('designation', models.CharField(blank=True, max_length=260, null=True)),
                ('department', models.CharField(blank=True, max_length=260, null=True)),
                ('work_for', models.CharField(blank=True, max_length=260, null=True)),
                ('emp_status', models.CharField(blank=True, max_length=260, null=True)),
            ],
            options={
                'db_table': 'production_user',
            },
        ),
    ]
