# Generated by Django 4.0 on 2022-01-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0005_productionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionuser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='productionuser',
            name='password',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
