# Generated by Django 4.0 on 2022-02-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0007_completedtask_currentworkingtasks_workingcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='device_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='model',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currentworkingtasks',
            name='device_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='currentworkingtasks',
            name='model',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='currentworkingtasks',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workingcount',
            name='device_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='workingcount',
            name='model',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='workingcount',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
