# Generated by Django 4.0 on 2022-01-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leadDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, max_length=120, null=True)),
                ('lead_status', models.CharField(blank=True, max_length=10, null=True)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_details',
            },
        ),
    ]
