# Generated by Django 4.0 on 2022-01-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=460, null=True)),
                ('c_email', models.CharField(blank=True, max_length=230, null=True)),
                ('c_address', models.CharField(blank=True, max_length=460, null=True)),
                ('c_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('client_status', models.CharField(blank=True, max_length=40, null=True)),
                ('lead_id', models.CharField(blank=True, max_length=20, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_details',
            },
        ),
        migrations.CreateModel(
            name='clientProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, max_length=20, null=True)),
                ('project_name', models.CharField(blank=True, max_length=110, null=True)),
                ('site_number', models.CharField(blank=True, max_length=10, null=True)),
                ('project_address', models.CharField(blank=True, max_length=460, null=True)),
                ('lead_status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'client_project_details',
            },
        ),
        migrations.CreateModel(
            name='leadReferances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_name', models.CharField(blank=True, max_length=160, null=True)),
                ('ref_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('ref_email', models.CharField(blank=True, max_length=140, null=True)),
                ('ref_address', models.CharField(blank=True, max_length=460, null=True)),
                ('lead_status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'lead_referances',
            },
        ),
        migrations.CreateModel(
            name='leadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(blank=True, max_length=40, null=True)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'lead_status',
            },
        ),
    ]
