# Generated by Django 4.0 on 2022-01-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_clientdetails_clientprojectdetails_leadreferances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='c_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
