# Generated by Django 4.0 on 2022-01-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_clientdetails_c_site_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='lead_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
