# Generated by Django 4.0 on 2022-01-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_clientdetails_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadreferances',
            name='ref_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
