# Generated by Django 4.0 on 2022-01-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_clientprojectdetails_ctime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='timestamp',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
