# Generated by Django 4.0 on 2022-01-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_clientdetails_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprojectdetails',
            name='timestamp',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='leaddetails',
            name='timestamp',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='leadreferances',
            name='timestamp',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
