# Generated by Django 4.0 on 2022-01-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0009_clientprojectdetails_timestamp_leaddetails_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='leadNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, max_length=120, null=True)),
                ('note', models.CharField(blank=True, max_length=4450, null=True)),
                ('next_follow', models.CharField(blank=True, max_length=150, null=True)),
                ('tied_up_date', models.CharField(blank=True, max_length=150, null=True)),
                ('lead_status', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'lead_notes',
            },
        ),
    ]
