# Generated by Django 4.0 on 2022-01-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_alter_leadnotes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='sales_person',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
